using Practice1.DayFive;
//using Practice1.DaySix;
using Practice1.DayThree;
using System.Net.Sockets;
using Practice1.DaySix1;
using Practice1.DayG7;
using Practice1.DaySix;
using Practice1.DayH8;
using Practice1.DaySix1;

//int v1 = 1000;
//Console.WriteLine($" v1:{v1}");
//Task1.DoTask(v1);
//Console.WriteLine($"V1:{v1}");
//Task1.DoTaskA(ref v1);
//Console.WriteLine($"v1:{v1}");
//ArrayDemo.FirstMethod();
//ArrayDemo.ArrayOverRun();
//ArrayDemo.TwoD();
//ArrayDemo.ThreeD();
//ArrayDemo.SortingArrays();
//ArrayDemo.UsingJaggedArrays();
//Employee.EmpArray();
//CollectionDemo.TestArrayList();
//CollectionDemo.GenericListInteger();
//CollectionDemo.GenericListString();
//CollectionDemo.GenericListDemoEmp();
//Anagrams.Anagram();
//SetDemo.SetStringDemo();
//SetDemo.TestGenericSortedSetInt();
//SetDemo.TestGenericSortedSetString();
//QueueDemo.TestQueue();
//StackDemo.StackDemoA();
//DictionaryDemo.HashtableDemo();
//EmployeeHashTableDemo.EmpHTDemo();
//DictionaryDemo.EmpDictionaryDemo();
//DictionaryDemo.TestSortedListA();
//DictionaryDemo.TestSortedListOfEmp();
//WorkingWithObjects.TestOne();
//WorkingWithObjects.TestTwo();
//GenericDemo.TestA();
//GenericDemo.TestB();
//ParametersDemo.TestByRefMethod();
//ParametersDemo.TestOutarameter();
//ParametersDemo.TestOptionalParameter();
//ParametersDemo.TestAddIntParams();
//DelegateDemo.TestOne();
//TestEmp.TestA();

//Tester.Test();
//LambdaDemo.DemoA();
//LambdaDemo.DemoB();
//LambdaDemo.DemoC();
//LambdaDemo.DemoD();
//LambdaDemo.DemoE();
//LambdaDemo.DemoF();
//LambdaDemo.TestEcho();
//LambdaDemo.TestDoTrans();

//ThreadDemo.DemoCurrentTH();
//ThreadDemo.DemoA();
//ThreadDemo.DemoB();
//ThreadDemo.DemoC();
//TestEvents.TestOne();


//StreamLesson.TestOne();
//StreamLesson.TestTwo();
//StreamLesson.TestThree();
//StreamLesson.TestNullableTypes();
//StreamReaderWriterLesson.MemStreamWriter();
//StreamReaderWriterLesson.MemStreamReader();
//BinaryStreamDemo.ReadBytesFromMemoryStream();
//BinaryStreamDemo.WriteBytesToMemoryStream();
//StreamReaderWriterLesson.WriteStringToMemoryStream();
//StreamReaderWriterLesson.ReadStringFromMemoryStream();
//StreamReaderWriterLesson.PeekAndReadCharacters();
//FileOperator.FileWriteAllLines();
//FileOperator.FileReadAllText();
//FileOperator.FileRename();
//FileOperator.ListDirectoryContent();
//FileOperator.ShowCurrentDirectory();
//FileOperator.CreateDirectory();
//FileOperator.DeleteDirectory();
//FileOperator.FileWriteAllText();
//FileOperator.StreamWriterDemo();
//FileOperator.StreamReaderFromFileDemo();
//Console.WriteLine(ImageCache.Logo);
//TestBinaryFormatter.SerializeCustomer();
//TestBinaryFormatter.DeSerializeCustomer();
//ClassA.TaskMethodA();
//TaskLessons.TestOne();
//ClassA.TaskMethodB();
//ClassA.TaskMethodC();
//ClassA.TaskMethodB1();
//TaskLessons.ContinueTask();
//Console.ReadLine();
//ClassA.ParentTask();
//ClassA.ChildTask();
//ClassA.ParentAndChild();
//TaskLessons.TestCancelToken();


Sample.QuestionThreeC();
Sample.QuestionFourC();
Sample.QuestionThreeE();
Sample.QuestionFour();

